name: Generate Snake

on:
  workflow_dispatch:  # Allows manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake GIF
        uses: Platane/snk@v3
        with:
          github_user_name: anestxx
          outputs: snake.gif?color_snake=orange&animate=true
          
      - name: Upload to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: output
          keep_files: false
